"""empty message

Revision ID: 10541ef486d4
Revises: 15fe102c44be
Create Date: 2014-11-05 03:23:12.432000

"""

# revision identifiers, used by Alembic.
revision = '10541ef486d4'
down_revision = '15fe102c44be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('schedule', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'schedule')
    ### end Alembic commands ###
