"""empty message

Revision ID: 122b6d3d06c8
Revises: 2211dfd9ffb1
Create Date: 2014-09-23 16:26:06.422000

"""

# revision identifiers, used by Alembic.
revision = '122b6d3d06c8'
down_revision = '2211dfd9ffb1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
