"""empty message

Revision ID: 19883bdde787
Revises: 5a7e4dde0687
Create Date: 2014-10-02 11:33:56.517000

"""

# revision identifiers, used by Alembic.
revision = '19883bdde787'
down_revision = '5a7e4dde0687'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('is_like', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('log_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('like_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_like', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], [u'log.id'], name=u'comments_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'comments_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('comment')
    ### end Alembic commands ###
