"""empty message

Revision ID: 19a9a90985e
Revises: 1014a9010601
Create Date: 2014-09-11 12:17:12.628000

"""

# revision identifiers, used by Alembic.
revision = '19a9a90985e'
down_revision = '1014a9010601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('log_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('log', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('log', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'user_id')
    op.drop_column('log', 'project_id')
    op.drop_column('group', 'project_id')
    op.drop_column('comment', 'user_id')
    op.drop_column('comment', 'log_id')
    ### end Alembic commands ###
