"""empty message

Revision ID: 1ad090774f6a
Revises: 185e82587b55
Create Date: 2014-11-27 13:58:10.739000

"""

# revision identifiers, used by Alembic.
revision = '1ad090774f6a'
down_revision = '185e82587b55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    ### end Alembic commands ###
