"""empty message

Revision ID: 1c806d0a1ed0
Revises: 5a8034e07c19
Create Date: 2014-10-02 11:06:40.516000

"""

# revision identifiers, used by Alembic.
revision = '1c806d0a1ed0'
down_revision = '5a8034e07c19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
