"""empty message

Revision ID: 1e5cae1060b2
Revises: 2f03052d64b4
Create Date: 2014-10-02 10:45:33.458000

"""

# revision identifiers, used by Alembic.
revision = '1e5cae1060b2'
down_revision = '2f03052d64b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
