"""empty message

Revision ID: 1f8bce9cd2ee
Revises: 122b6d3d06c8
Create Date: 2014-10-02 01:09:01.849000

"""

# revision identifiers, used by Alembic.
revision = '1f8bce9cd2ee'
down_revision = '122b6d3d06c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
