"""empty message

Revision ID: 2211dfd9ffb1
Revises: 4d7dfd6e8d8d
Create Date: 2014-09-23 01:32:15.544000

"""

# revision identifiers, used by Alembic.
revision = '2211dfd9ffb1'
down_revision = '4d7dfd6e8d8d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_column('project', 'group_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('group', 'project_id')
    ### end Alembic commands ###
