"""empty message

Revision ID: 234aa58ad254
Revises: 43389140316
Create Date: 2014-10-02 02:38:45.528000

"""

# revision identifiers, used by Alembic.
revision = '234aa58ad254'
down_revision = '43389140316'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
