"""empty message

Revision ID: 25dc6b7c6aad
Revises: 33986fac90f8
Create Date: 2014-10-02 22:26:01.589000

"""

# revision identifiers, used by Alembic.
revision = '25dc6b7c6aad'
down_revision = '33986fac90f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('hoho', sa.String(length=23), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'hoho')
    ### end Alembic commands ###
