"""empty message

Revision ID: 26f966bd86a2
Revises: 28813e69abe7
Create Date: 2015-03-03 13:45:12.393000

"""

# revision identifiers, used by Alembic.
revision = '26f966bd86a2'
down_revision = '28813e69abe7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favlist', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favlist')
    ### end Alembic commands ###
