"""empty message

Revision ID: 292fbaadfa36
Revises: 1e5cae1060b2
Create Date: 2014-10-02 10:46:17.542000

"""

# revision identifiers, used by Alembic.
revision = '292fbaadfa36'
down_revision = '1e5cae1060b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
