"""empty message

Revision ID: 294a552b47ee
Revises: 56ed5df41b66
Create Date: 2014-10-02 22:24:12.491000

"""

# revision identifiers, used by Alembic.
revision = '294a552b47ee'
down_revision = '56ed5df41b66'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
