"""empty message

Revision ID: 29ccb17f4b2e
Revises: 2370423668f8
Create Date: 2014-10-02 10:53:21.202000

"""

# revision identifiers, used by Alembic.
revision = '29ccb17f4b2e'
down_revision = '2370423668f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('project_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'project_id')
    ### end Alembic commands ###
