"""empty message

Revision ID: 2c0f900d4c78
Revises: 2a03c7324aaa
Create Date: 2015-03-16 23:01:04.489000

"""

# revision identifiers, used by Alembic.
revision = '2c0f900d4c78'
down_revision = '2a03c7324aaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('invites', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('invites', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invites')
    op.drop_column('project', 'invites')
    ### end Alembic commands ###
