"""empty message

Revision ID: 2f03052d64b4
Revises: 500112df43ba
Create Date: 2014-10-02 10:44:30.898000

"""

# revision identifiers, used by Alembic.
revision = '2f03052d64b4'
down_revision = '500112df43ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
