"""empty message

Revision ID: 301062811686
Revises: 4f5c9d9cdae9
Create Date: 2014-10-16 05:17:17.323000

"""

# revision identifiers, used by Alembic.
revision = '301062811686'
down_revision = '4f5c9d9cdae9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'user_id')
    ### end Alembic commands ###
