"""empty message

Revision ID: 33986fac90f8
Revises: 294a552b47ee
Create Date: 2014-10-02 22:25:32.670000

"""

# revision identifiers, used by Alembic.
revision = '33986fac90f8'
down_revision = '294a552b47ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
