"""empty message

Revision ID: 395710c8e877
Revises: 1f8bce9cd2ee
Create Date: 2014-10-02 01:42:19.338000

"""

# revision identifiers, used by Alembic.
revision = '395710c8e877'
down_revision = '1f8bce9cd2ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
