"""empty message

Revision ID: 40233f4143b7
Revises: 4746e9944b2
Create Date: 2014-10-02 03:46:00.039000

"""

# revision identifiers, used by Alembic.
revision = '40233f4143b7'
down_revision = '4746e9944b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
