"""empty message

Revision ID: 4163e607c487
Revises: 1c806d0a1ed0
Create Date: 2014-10-02 11:09:38.224000

"""

# revision identifiers, used by Alembic.
revision = '4163e607c487'
down_revision = '1c806d0a1ed0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
