"""empty message

Revision ID: 43389140316
Revises: 395710c8e877
Create Date: 2014-10-02 02:00:54.143000

"""

# revision identifiers, used by Alembic.
revision = '43389140316'
down_revision = '395710c8e877'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
