"""empty message

Revision ID: 4412f2af822f
Revises: 4fe1920d870
Create Date: 2014-10-02 03:37:07.630000

"""

# revision identifiers, used by Alembic.
revision = '4412f2af822f'
down_revision = '4fe1920d870'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
