"""empty message

Revision ID: 4746e9944b2
Revises: 4412f2af822f
Create Date: 2014-10-02 03:39:52.853000

"""

# revision identifiers, used by Alembic.
revision = '4746e9944b2'
down_revision = '4412f2af822f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
