"""empty message

Revision ID: 484a822159a2
Revises: 40233f4143b7
Create Date: 2014-10-02 04:10:00.416000

"""

# revision identifiers, used by Alembic.
revision = '484a822159a2'
down_revision = '40233f4143b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
