"""empty message

Revision ID: 49350710d910
Revises: 10541ef486d4
Create Date: 2014-11-06 01:51:48.775000

"""

# revision identifiers, used by Alembic.
revision = '49350710d910'
down_revision = '10541ef486d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
