"""empty message

Revision ID: 4d7dfd6e8d8d
Revises: 19a9a90985e
Create Date: 2014-09-23 01:03:56.037000

"""

# revision identifiers, used by Alembic.
revision = '4d7dfd6e8d8d'
down_revision = '19a9a90985e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'project_id')
    op.add_column('project', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'group_id')
    op.drop_column('project', 'description')
    op.add_column('group', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
