"""empty message

Revision ID: 4fe1920d870
Revises: 234aa58ad254
Create Date: 2014-10-02 03:20:49.263000

"""

# revision identifiers, used by Alembic.
revision = '4fe1920d870'
down_revision = '234aa58ad254'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
