"""empty message

Revision ID: 500112df43ba
Revises: 484a822159a2
Create Date: 2014-10-02 10:24:06.471000

"""

# revision identifiers, used by Alembic.
revision = '500112df43ba'
down_revision = '484a822159a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'project_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
