"""empty message

Revision ID: 550f2a31f1af
Revises: 292fbaadfa36
Create Date: 2014-10-02 10:48:37.066000

"""

# revision identifiers, used by Alembic.
revision = '550f2a31f1af'
down_revision = '292fbaadfa36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    ### end Alembic commands ###
