"""empty message

Revision ID: 56ed5df41b66
Revises: 19883bdde787
Create Date: 2014-10-02 11:59:05.932000

"""

# revision identifiers, used by Alembic.
revision = '56ed5df41b66'
down_revision = '19883bdde787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('file_key', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'file_key')
    ### end Alembic commands ###
