"""empty message

Revision ID: 5841f6564a28
Revises: 4163e607c487
Create Date: 2014-10-02 11:17:20.616000

"""

# revision identifiers, used by Alembic.
revision = '5841f6564a28'
down_revision = '4163e607c487'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
