"""empty message

Revision ID: 5a8034e07c19
Revises: 27b636901d52
Create Date: 2014-10-02 11:02:48.059000

"""

# revision identifiers, used by Alembic.
revision = '5a8034e07c19'
down_revision = '27b636901d52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
