"""empty message

Revision ID: ef374d40181
Revises: 26f966bd86a2
Create Date: 2015-03-06 13:51:35.951000

"""

# revision identifiers, used by Alembic.
revision = 'ef374d40181'
down_revision = '26f966bd86a2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.add_column('user', sa.Column('mprojects', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mprojects')
    op.create_table('favorite',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
